
Enum operation_type {
  increase
  decrease
}

Enum debit_account_type {
  card
  cash
  deposit
  saving
  other 
}

Enum operation_category_purpose {
  mandatory
  desirable
  optional
}

Enum planned_operation_status {
  canceled
  draft
  pending // partially resolved
  resolved
}

Enum operation_category_type {
  public
  private
}

Table users {
  id string [primary key]
  email string [unique]
  first_name string
  last_name string
  password string
}

Table user_operation_category {
  id string [primary key]
  user_id string [ref: < users.id]
  operation_category_id string [ref: < operation_categories.id]
}

Table operation_categories {
  id string [primary key]
  title string [unique, not null]
  purpose operation_category_purpose
  type operation_category_type
}

Table operations {
  id string [primary key]
  amount integer [not null]
  description string
  type operation_type
  processed_at timestamp
  user_id string [not null, ref: > users.id]
  debit_account_id string [not null, ref: > debit_accounts.id]
  operation_category_id string [ref: > operation_categories.id]
  // currency_id string [not null, ref: > currencies.id] -- get currency from related debit_account
}

Table transfers {
  id string [primary key]
  amount integer [not null]
  description string
  source_operation_id string [ref: - operations.id]
  target_operation_id string [ref: - operations.id]
}

Table planned_transfers {
  id string [primary key]
  amount integer [not null]
  description string
  source_operation_id string [ref: - operations.id]
  target_operation_id string [ref: - operations.id]
  transfer_id string [ref: > operation_categories.id]
}

Table debit_accounts {
  id string [primary key]
  user_id string [ref: > users.id]
  title string
  type debit_account_type
  amount integer [not null]
  currency_id string [ref: > currencies.id]
}

Table currencies {
  id string [primary key]
  title string [unique, not null]
}

Table budget_plans {
  id string [primary key]
  start_date naive_datetime [not null]
  period_in_days integer [not null]
  description string
  user_id string [not null, ref: > users.id]
}

Table planned_operations {
  id string [primary key]
  plan_id string [ref: > budget_plans.id]
  operation_id string [ref: < operations.id]
  amount integer [not null]
  status planned_operation_status
  type operation_type
  operation_category_id string [ref: > operation_categories.id]
  // currency_id string [not null, ref: > currencies.id] -- get currency from related debit_account
}

Table operations_links {
  id string [primary key]
  operation_id string [ref: - operations.id]
  planned_operation_id string [ref: - planned_operations.id]
}
